name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  deploy-to-cloudflare:
    name: Automatic Cloudflare Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '3.57.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            SUPABASE_URL
            SUPABASE_KEY
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
